### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by cternes** [codecutout/MockHttpClient#3]
Are you still supporting this library? Are PRs welcome?

**Comment by alex-davies** [comment]
It is still casually supported, I am always happy to accept PRs, but cant give any SLA guarantees

**Comment by cternes** [comment]
@alex-davies Of course, no  SLAs expected 😄 But good, then I will provide some PRs.
Thanks for the lib, it's a nice piece and I saw nothing as simple as this for mocking HttpClient 👍
